export type Dish = {
  id: string;
  region: "armenian" | "latin" | "asian" | "european";
  country: { en: string; hy: string; ru: string };
  flag: string;
  name: { en: string; hy: string; ru: string };
  description: { en: string; hy: string; ru: string };
  cookTime: number; // minutes
  difficulty: "Easy" | "Medium";
  price: number;
  emoji: string;
  photo: string;
  tags: string[];
  popular?: boolean;
};

export const dishes: Dish[] = [
  // ── ARMENIAN ──
  {
    id: "dolma",
    region: "armenian",
    country: { en: "Armenia", hy: "Հայاстан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Dolma", hy: "Տolma", ru: "Долма" },
    description: { en: "Vine leaves stuffed with spiced lamb and rice, simmered in broth. Armenia's most beloved dish.", hy: "Tapatakhnotin mej khndzori terts ltsats aghjikanerov yev brindzhov.", ru: "Виноградные листья, фаршированные ягнёнком и рисом. Любимое блюдо Армении." },
    cookTime: 35,
    difficulty: "Medium",
    price: 4200,
    emoji: "🫙",
    photo: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
    tags: ["classic", "hearty"],
    popular: true,
  },
  {
    id: "khorovats",
    region: "armenian",
    country: { en: "Armenia", hy: "Հайастан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Khorovats (BBQ)", hy: "Ховorвац", ru: "Хоровац (шашлык)" },
    description: { en: "Armenian BBQ — marinated pork or lamb grilled over charcoal. The smell alone is worth it.", hy: "Hаykakan barbeku — marinated khoz kam garn.", ru: "Армянский шашлык — маринованная свинина или ягнёнок на углях." },
    cookTime: 30,
    difficulty: "Easy",
    price: 5500,
    emoji: "🍖",
    photo: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    tags: ["bbq", "protein", "classic"],
    popular: true,
  },
  {
    id: "spas",
    region: "armenian",
    country: { en: "Armenia", hy: "Hайастан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Spas Soup", hy: "Սpaс", ru: "Суп Спас" },
    description: { en: "Warm yogurt soup with wheat and herbs. Comforting, creamy and uniquely Armenian.", hy: "Taz matznayin soup dzavarov yev kanaluk bujabuyserov.", ru: "Тёплый йогуртовый суп с пшеницей и зеленью. Уютный и кремовый." },
    cookTime: 20,
    difficulty: "Easy",
    price: 2800,
    emoji: "🍲",
    photo: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    tags: ["soup", "quick", "vegetarian"],
  },
  {
    id: "manti",
    region: "armenian",
    country: { en: "Armenia", hy: "Hайастан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Manti (Baked Dumplings)", hy: "Маnтi", ru: "Манты запечённые" },
    description: { en: "Tiny open-top dumplings baked until golden, served with yogurt and paprika butter. Addictive.", hy: "Peqvats manrer madzunov yev paprikayin karakhnov.", ru: "Маленькие открытые пельмени, запечённые до золотистой корочки, подаются с йогуртом и маслом паприки." },
    cookTime: 40,
    difficulty: "Medium",
    price: 3800,
    emoji: "🥟",
    photo: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80",
    tags: ["classic", "hearty", "baked"],
    popular: true,
  },
  {
    id: "ghapama",
    region: "armenian",
    country: { en: "Armenia", hy: "Hайастан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Ghapama (Stuffed Pumpkin)", hy: "Гапaмa", ru: "Гапама (фаршированная тыква)" },
    description: { en: "Pumpkin stuffed with rice, dried fruits and honey — baked whole. A festive showstopper.", hy: "Misket ltsats brindzhov, chir mrluknerov yev medov.", ru: "Тыква, фаршированная рисом, сухофруктами и мёдом — запекается целиком. Праздничное блюдо." },
    cookTime: 45,
    difficulty: "Medium",
    price: 3500,
    emoji: "🎃",
    photo: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=800&q=80",
    tags: ["festive", "vegetarian", "sweet"],
  },
  {
    id: "herb-frittata",
    region: "armenian",
    country: { en: "Armenia", hy: "Hайастан", ru: "Армения" },
    flag: "🇦🇲",
    name: { en: "Herb Frittata (Kuku)", hy: "Куку", ru: "Фриттата с зеленью (Куку)" },
    description: { en: "A thick Persian-Armenian egg cake packed with fresh herbs — parsley, dill, walnuts and barberries.", hy: "Hаст dzvayin kek ltsats taza bujabuyserov — petrusinia, dill, enjuyz.", ru: "Плотный яичный пирог с зеленью — петрушкой, укропом, грецкими орехами и барбарисом." },
    cookTime: 20,
    difficulty: "Easy",
    price: 2500,
    emoji: "🥚",
    photo: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=80",
    tags: ["quick", "vegetarian", "breakfast"],
  },
  // ── LATIN ──
  {
    id: "chicken-tacos",
    region: "latin",
    country: { en: "Mexico", hy: "Мексika", ru: "Мексика" },
    flag: "🇲🇽",
    name: { en: "Chicken Tinga Tacos", hy: "Таkos Tinga", ru: "Тако с тингой" },
    description: { en: "Smoky chipotle-braised chicken in warm corn tortillas with pickled onion and cilantro.", hy: "Chipotle-ov yepu hav taq tortillanersum.", ru: "Курица в копчёном чипотле в тёплых тортильях с маринованным луком." },
    cookTime: 30,
    difficulty: "Easy",
    price: 4800,
    emoji: "🌮",
    photo: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    tags: ["street food", "spicy"],
    popular: true,
  },
  {
    id: "lomo-saltado",
    region: "latin",
    country: { en: "Peru", hy: "Пeру", ru: "Перу" },
    flag: "🇵🇪",
    name: { en: "Lomo Saltado", hy: "Ломo Saltado", ru: "Ломо Сальтадо" },
    description: { en: "Wok-fried beef strips with tomatoes, soy sauce, chips and rice. Peru's most iconic dish.", hy: "Wok-um tapakats khozi strips pomidorov, soya-yov.", ru: "Говядина в воке с помидорами, соевым соусом, картошкой и рисом." },
    cookTime: 25,
    difficulty: "Easy",
    price: 6200,
    emoji: "🥩",
    photo: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
    tags: ["wok", "hearty", "protein"],
  },
  {
    id: "arepas",
    region: "latin",
    country: { en: "Colombia", hy: "Кolumbia", ru: "Колумбия" },
    flag: "🇨🇴",
    name: { en: "Arepas with Cheese", hy: "Arepas kaseriov", ru: "Арепас с сыром" },
    description: { en: "Crispy grilled corn cakes stuffed with melted mozzarella. Simple, satisfying, and impossible to stop eating.", hy: "Кhrtkhroth yegetatsori kek hals mozzarellayov.", ru: "Хрустящие кукурузные лепёшки с тающей моцареллой." },
    cookTime: 20,
    difficulty: "Easy",
    price: 3200,
    emoji: "🫓",
    photo: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80",
    tags: ["quick", "vegetarian", "snack"],
  },
  {
    id: "ceviche",
    region: "latin",
    country: { en: "Peru", hy: "Пeру", ru: "Перу" },
    flag: "🇵🇪",
    name: { en: "Ceviche", hy: "Сeвиче", ru: "Севиче" },
    description: { en: "Fresh sea bass cured purely by lime juice with red onion and chili. No heat needed.", hy: "Taza juk limon husov, karmir soukhov. Krak petk che.", ru: "Свежий морской окунь, маринованный лаймом с красным луком и чили. Без тепловой обработки." },
    cookTime: 20,
    difficulty: "Easy",
    price: 5800,
    emoji: "🐟",
    photo: "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800&q=80",
    tags: ["fresh", "no-cook", "light"],
    popular: true,
  },
  // ── ASIAN ──
  {
    id: "ramen",
    region: "asian",
    country: { en: "Japan", hy: "Ճaponia", ru: "Япония" },
    flag: "🇯🇵",
    name: { en: "Tonkotsu Ramen", hy: "Тonkotsu Ramen", ru: "Тонкоцу Рамен" },
    description: { en: "Rich pork broth with silky noodles, chashu belly and a soft-boiled marinated egg.", hy: "Hаrust khozi arganakn mekaron, chashu yev dzviov.", ru: "Насыщенный свиной бульон с лапшой, тяшю и маринованным яйцом." },
    cookTime: 35,
    difficulty: "Medium",
    price: 5200,
    emoji: "🍜",
    photo: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80",
    tags: ["soup", "hearty", "umami"],
    popular: true,
  },
  {
    id: "pad-thai",
    region: "asian",
    country: { en: "Thailand", hy: "Тailаnd", ru: "Таиланд" },
    flag: "🇹🇭",
    name: { en: "Pad Thai", hy: "Пад Тай", ru: "Пад Тай" },
    description: { en: "Stir-fried rice noodles with shrimp, tamarind, peanuts and that unmistakable wok flavour.", hy: "Tapakats mekaron shrimperi, tamarind-i yev enkuyznerov.", ru: "Жареная рисовая лапша с креветками, тамариндом и арахисом." },
    cookTime: 25,
    difficulty: "Easy",
    price: 4900,
    emoji: "🥘",
    photo: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&q=80",
    tags: ["wok", "noodles", "quick"],
  },
  {
    id: "green-curry",
    region: "asian",
    country: { en: "Thailand", hy: "Тailаnd", ru: "Таиланд" },
    flag: "🇹🇭",
    name: { en: "Green Curry", hy: "Кanach Кари", ru: "Зелёное карри" },
    description: { en: "Coconut milk curry with chicken, Thai basil and jasmine rice. Fragrant, creamy and deeply satisfying.", hy: "Кokosayin karri hav, thai basiliкov yev brindzhov.", ru: "Карри на кокосовом молоке с курицей, тайским базиликом и жасминовым рисом." },
    cookTime: 25,
    difficulty: "Easy",
    price: 4600,
    emoji: "🍛",
    photo: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    tags: ["curry", "coconut", "quick"],
    popular: true,
  },
  {
    id: "gyoza",
    region: "asian",
    country: { en: "Japan", hy: "Ճaponia", ru: "Япония" },
    flag: "🇯🇵",
    name: { en: "Gyoza (Pan-fried Dumplings)", hy: "Гйoza", ru: "Гёдза (жареные пельмени)" },
    description: { en: "Crispy-bottomed pan-fried dumplings with pork and cabbage filling, served with ponzu.", hy: "Кhrtkhroth tapakats manrer khoz yev kapustayov.", ru: "Хрустящие снизу пельмени со свининой и капустой, подаются с понзу." },
    cookTime: 25,
    difficulty: "Medium",
    price: 3800,
    emoji: "🥟",
    photo: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    tags: ["dumplings", "crispy", "snack"],
  },
  // ── EUROPEAN ──
  {
    id: "carbonara",
    region: "european",
    country: { en: "Italy", hy: "Италia", ru: "Италия" },
    flag: "🇮🇹",
    name: { en: "Spaghetti Carbonara", hy: "Спагетти Карбонara", ru: "Спагетти Карбонара" },
    description: { en: "Silky egg-and-Pecorino sauce with crispy pancetta. The Roman classic done right.", hy: "Мetaxe dzvayin sous pancettayov. Hаykavan klassik.", ru: "Шёлковый соус из яиц и Пекорино с хрустящей панчеттой. Римская классика." },
    cookTime: 25,
    difficulty: "Medium",
    price: 4400,
    emoji: "🍝",
    photo: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80",
    tags: ["pasta", "classic", "quick"],
    popular: true,
  },
  {
    id: "french-onion-soup",
    region: "european",
    country: { en: "France", hy: "Фransia", ru: "Франция" },
    flag: "🇫🇷",
    name: { en: "French Onion Soup", hy: "Французский луковый суп", ru: "Французский луковый суп" },
    description: { en: "Slow-caramelised onion soup with a bubbling gruyère crouton on top. Pure Paris comfort.", hy: "Аllari soup gruyer-i yev krutoni het. Parisyan hamb.", ru: "Медленно карамелизованный луковый суп с пузырящимся грюйером. Комфорт по-парижски." },
    cookTime: 45,
    difficulty: "Medium",
    price: 3600,
    emoji: "🧅",
    photo: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    tags: ["soup", "classic", "winter"],
  },
  {
    id: "patatas-bravas",
    region: "european",
    country: { en: "Spain", hy: "Испания", ru: "Испания" },
    flag: "🇪🇸",
    name: { en: "Patatas Bravas + Gambas", hy: "Пататас Бравас", ru: "Патас Бравас + Гамбас" },
    description: { en: "Crispy potatoes with smoky tomato sauce and garlic shrimp sizzling in olive oil.", hy: "Кhrtkhroth kartofil paprikayin sousov yev sxtorayin shrimperi.", ru: "Хрустящий картофель с пряным томатным соусом и чесночными креветками." },
    cookTime: 30,
    difficulty: "Easy",
    price: 4800,
    emoji: "🦐",
    photo: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80",
    tags: ["tapas", "crispy", "sharing"],
  },
  {
    id: "risotto",
    region: "european",
    country: { en: "Italy", hy: "Италia", ru: "Италия" },
    flag: "🇮🇹",
    name: { en: "Risotto al Limone", hy: "Ризотто аль лиmonо", ru: "Ризотто аль Лимоне" },
    description: { en: "Creamy Arborio rice finished with lemon zest and Parmesan. Simple but impossibly elegant.", hy: "Karakhnayin brindzh limon yev parmesan-ov. Hamest bayts eleganт.", ru: "Кремовый рис арборио с лимонной цедрой и пармезаном. Просто, но невероятно элегантно." },
    cookTime: 35,
    difficulty: "Medium",
    price: 4100,
    emoji: "🫕",
    photo: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    tags: ["pasta", "vegetarian", "elegant"],
  },
];

export const dishRegions = [
  { id: "all",      label: { en: "All dishes",  hy: "Bolor", ru: "Все" } },
  { id: "armenian", label: { en: "🇦🇲 Armenian", hy: "🇦🇲 Hаykakan", ru: "🇦🇲 Армянские" } },
  { id: "latin",    label: { en: "🌎 Latin",     hy: "🌎 Latin", ru: "🌎 Латинские" } },
  { id: "asian",    label: { en: "🌏 Asian",     hy: "🌏 Asian", ru: "🌏 Азиатские" } },
  { id: "european", label: { en: "🌍 European",  hy: "🌍 Europen", ru: "🌍 Европейские" } },
] as const;

// Suggest 5 dishes: 2 Armenian + 1 Latin + 1 Asian + 1 European
export function suggestWeek(existing?: string[]): Dish[] {
  const exclude = existing || [];
  const pick = (region: Dish["region"], count: number) => {
    const pool = dishes.filter(d => d.region === region && !exclude.includes(d.id));
    const popular = pool.filter(d => d.popular);
    const sorted = [...popular, ...pool.filter(d => !d.popular)];
    return sorted.slice(0, count);
  };
  return [
    ...pick("armenian", 2),
    ...pick("latin", 1),
    ...pick("asian", 1),
    ...pick("european", 1),
  ];
}
